version: "3.3"

services:
  charismahair:
    image: elliotjreed/www.charismahair.co.uk
    container_name: charismahair
    restart: always
    networks:
      - elliotjreed
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:www.charismahair.co.uk"
      - "traefik.protocol=http"
      - "traefik.port=82"

networks:
  elliotjreed:
  web:
    external: true
